-- =========================================================
-- Migrazione Supabase / PostgreSQL
-- Progetto: Scraper gerarchico bandi OpenCoesione
-- =========================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Relazione bando -> beneficiari
CREATE TABLE IF NOT EXISTS public.bando_beneficiari (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bando_id integer NOT NULL,
  beneficiario_id integer NOT NULL,
  creato_il timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bando_beneficiari_bando_id_fkey
    FOREIGN KEY (bando_id) REFERENCES public.bando(id) ON DELETE CASCADE,
  CONSTRAINT bando_beneficiari_beneficiario_id_fkey
    FOREIGN KEY (beneficiario_id) REFERENCES public.beneficiari(id) ON DELETE RESTRICT,
  CONSTRAINT bando_beneficiari_unique UNIQUE (bando_id, beneficiario_id)
);

CREATE INDEX IF NOT EXISTS idx_bando_beneficiari_bando_id
  ON public.bando_beneficiari (bando_id);

CREATE INDEX IF NOT EXISTS idx_bando_beneficiari_beneficiario_id
  ON public.bando_beneficiari (beneficiario_id);

-- 2) Retry / pending su bando
ALTER TABLE public.bando
  ADD COLUMN IF NOT EXISTS stato_processing character varying NOT NULL DEFAULT 'ready',
  ADD COLUMN IF NOT EXISTS retry_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_retry integer NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS next_retry_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS last_error_type character varying,
  ADD COLUMN IF NOT EXISTS last_error_message text,
  ADD COLUMN IF NOT EXISTS last_error_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS ai_processing_required boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ai_processing_status character varying NOT NULL DEFAULT 'not_required',
  ADD COLUMN IF NOT EXISTS ai_last_attempt_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS ocr_required boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ocr_status character varying NOT NULL DEFAULT 'not_required',
  ADD COLUMN IF NOT EXISTS ocr_last_attempt_at timestamp with time zone;

ALTER TABLE public.bando
  DROP CONSTRAINT IF EXISTS bando_stato_processing_check;

ALTER TABLE public.bando
  ADD CONSTRAINT bando_stato_processing_check
  CHECK (stato_processing IN ('ready', 'pending', 'processing', 'failed_final'));

ALTER TABLE public.bando
  DROP CONSTRAINT IF EXISTS bando_ai_processing_status_check;

ALTER TABLE public.bando
  ADD CONSTRAINT bando_ai_processing_status_check
  CHECK (ai_processing_status IN ('not_required', 'queued', 'processing', 'completed', 'failed'));

ALTER TABLE public.bando
  DROP CONSTRAINT IF EXISTS bando_ocr_status_check;

ALTER TABLE public.bando
  ADD CONSTRAINT bando_ocr_status_check
  CHECK (ocr_status IN ('not_required', 'queued', 'processing', 'completed', 'failed'));

CREATE INDEX IF NOT EXISTS idx_bando_stato_processing
  ON public.bando (stato_processing);

CREATE INDEX IF NOT EXISTS idx_bando_next_retry_at
  ON public.bando (next_retry_at);

CREATE INDEX IF NOT EXISTS idx_bando_ai_processing_required
  ON public.bando (ai_processing_required);

CREATE INDEX IF NOT EXISTS idx_bando_ai_processing_status
  ON public.bando (ai_processing_status);

CREATE INDEX IF NOT EXISTS idx_bando_ocr_required
  ON public.bando (ocr_required);

CREATE INDEX IF NOT EXISTS idx_bando_ocr_status
  ON public.bando (ocr_status);

-- 3) Retry / pending su fonte
ALTER TABLE public.fonte
  ADD COLUMN IF NOT EXISTS stato_processing character varying NOT NULL DEFAULT 'ready',
  ADD COLUMN IF NOT EXISTS retry_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_retry integer NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS next_retry_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS last_error_type character varying,
  ADD COLUMN IF NOT EXISTS last_error_message text,
  ADD COLUMN IF NOT EXISTS last_error_at timestamp with time zone;

ALTER TABLE public.fonte
  DROP CONSTRAINT IF EXISTS fonte_stato_processing_check;

ALTER TABLE public.fonte
  ADD CONSTRAINT fonte_stato_processing_check
  CHECK (stato_processing IN ('ready', 'pending', 'processing', 'failed_final'));

CREATE INDEX IF NOT EXISTS idx_fonte_stato_processing
  ON public.fonte (stato_processing);

CREATE INDEX IF NOT EXISTS idx_fonte_next_retry_at
  ON public.fonte (next_retry_at);

CREATE INDEX IF NOT EXISTS idx_fonte_categoria_programma_id
  ON public.fonte (categoria_programma_id);

CREATE INDEX IF NOT EXISTS idx_fonte_tipologia_programma_id
  ON public.fonte (tipologia_programma_id);

-- 4) Errori definitivi
CREATE TABLE IF NOT EXISTS public.scraping_errori_definitivi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid,
  scraping_log_id integer,
  fonte_id integer,
  bando_id integer,
  entity_type character varying NOT NULL,
  entity_url text,
  errore_tipo character varying NOT NULL,
  errore_messaggio text,
  errore_stack text,
  http_status_code integer,
  retry_count integer NOT NULL DEFAULT 0,
  contesto jsonb,
  creato_il timestamp with time zone NOT NULL DEFAULT now(),
  risolto boolean NOT NULL DEFAULT false,
  risolto_il timestamp with time zone,
  note_risoluzione text,
  CONSTRAINT scraping_errori_definitivi_entity_type_check
    CHECK (entity_type IN ('fonte', 'bando', 'documento', 'ai_job', 'ocr_job')),
  CONSTRAINT scraping_errori_definitivi_scraping_log_id_fkey
    FOREIGN KEY (scraping_log_id) REFERENCES public.scraping_log(id) ON DELETE SET NULL,
  CONSTRAINT scraping_errori_definitivi_fonte_id_fkey
    FOREIGN KEY (fonte_id) REFERENCES public.fonte(id) ON DELETE SET NULL,
  CONSTRAINT scraping_errori_definitivi_bando_id_fkey
    FOREIGN KEY (bando_id) REFERENCES public.bando(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_scraping_errori_definitivi_fonte_id
  ON public.scraping_errori_definitivi (fonte_id);

CREATE INDEX IF NOT EXISTS idx_scraping_errori_definitivi_bando_id
  ON public.scraping_errori_definitivi (bando_id);

CREATE INDEX IF NOT EXISTS idx_scraping_errori_definitivi_entity_type
  ON public.scraping_errori_definitivi (entity_type);

CREATE INDEX IF NOT EXISTS idx_scraping_errori_definitivi_risolto
  ON public.scraping_errori_definitivi (risolto);

CREATE INDEX IF NOT EXISTS idx_scraping_errori_definitivi_creato_il
  ON public.scraping_errori_definitivi (creato_il DESC);

-- 5) Coda AI asincrona
CREATE TABLE IF NOT EXISTS public.ai_job_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  bando_id integer NOT NULL,
  stato character varying NOT NULL DEFAULT 'queued',
  tipo_job character varying NOT NULL DEFAULT 'classificazione',
  priorita integer NOT NULL DEFAULT 100,
  tentativi integer NOT NULL DEFAULT 0,
  max_tentativi integer NOT NULL DEFAULT 3,
  disponibile_da timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  errore_tipo character varying,
  errore_messaggio text,
  payload jsonb NOT NULL,
  risultato jsonb,
  creato_il timestamp with time zone NOT NULL DEFAULT now(),
  aggiornato_il timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_job_queue_job_uuid_key UNIQUE (job_uuid),
  CONSTRAINT ai_job_queue_bando_id_fkey
    FOREIGN KEY (bando_id) REFERENCES public.bando(id) ON DELETE CASCADE,
  CONSTRAINT ai_job_queue_stato_check
    CHECK (stato IN ('queued', 'processing', 'completed', 'failed', 'cancelled')),
  CONSTRAINT ai_job_queue_tipo_job_check
    CHECK (tipo_job IN ('classificazione', 'estrazione_mancanti', 'riclassificazione'))
);

CREATE INDEX IF NOT EXISTS idx_ai_job_queue_stato
  ON public.ai_job_queue (stato);

CREATE INDEX IF NOT EXISTS idx_ai_job_queue_disponibile_da
  ON public.ai_job_queue (disponibile_da);

CREATE INDEX IF NOT EXISTS idx_ai_job_queue_bando_id
  ON public.ai_job_queue (bando_id);

CREATE INDEX IF NOT EXISTS idx_ai_job_queue_priorita_disponibile
  ON public.ai_job_queue (priorita, disponibile_da);

-- 6) Coda OCR asincrona
CREATE TABLE IF NOT EXISTS public.ocr_job_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  bando_id integer,
  fonte_id integer,
  url_documento text NOT NULL,
  stato character varying NOT NULL DEFAULT 'queued',
  tentativi integer NOT NULL DEFAULT 0,
  max_tentativi integer NOT NULL DEFAULT 3,
  disponibile_da timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  errore_tipo character varying,
  errore_messaggio text,
  payload jsonb,
  testo_estratto text,
  metadati_ocr jsonb,
  creato_il timestamp with time zone NOT NULL DEFAULT now(),
  aggiornato_il timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ocr_job_queue_job_uuid_key UNIQUE (job_uuid),
  CONSTRAINT ocr_job_queue_bando_id_fkey
    FOREIGN KEY (bando_id) REFERENCES public.bando(id) ON DELETE SET NULL,
  CONSTRAINT ocr_job_queue_fonte_id_fkey
    FOREIGN KEY (fonte_id) REFERENCES public.fonte(id) ON DELETE SET NULL,
  CONSTRAINT ocr_job_queue_stato_check
    CHECK (stato IN ('queued', 'processing', 'completed', 'failed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_ocr_job_queue_stato
  ON public.ocr_job_queue (stato);

CREATE INDEX IF NOT EXISTS idx_ocr_job_queue_disponibile_da
  ON public.ocr_job_queue (disponibile_da);

CREATE INDEX IF NOT EXISTS idx_ocr_job_queue_bando_id
  ON public.ocr_job_queue (bando_id);

CREATE INDEX IF NOT EXISTS idx_ocr_job_queue_fonte_id
  ON public.ocr_job_queue (fonte_id);

-- 7) Trigger updated_at / aggiornato_il
CREATE OR REPLACE FUNCTION public.set_current_timestamp_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_current_timestamp_aggiornato_il()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.aggiornato_il = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_bando_set_updated_at ON public.bando;
CREATE TRIGGER trg_bando_set_updated_at
BEFORE UPDATE ON public.bando
FOR EACH ROW
EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_fonte_set_updated_at ON public.fonte;
CREATE TRIGGER trg_fonte_set_updated_at
BEFORE UPDATE ON public.fonte
FOR EACH ROW
EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_ai_job_queue_set_aggiornato_il ON public.ai_job_queue;
CREATE TRIGGER trg_ai_job_queue_set_aggiornato_il
BEFORE UPDATE ON public.ai_job_queue
FOR EACH ROW
EXECUTE FUNCTION public.set_current_timestamp_aggiornato_il();

DROP TRIGGER IF EXISTS trg_ocr_job_queue_set_aggiornato_il ON public.ocr_job_queue;
CREATE TRIGGER trg_ocr_job_queue_set_aggiornato_il
BEFORE UPDATE ON public.ocr_job_queue
FOR EACH ROW
EXECUTE FUNCTION public.set_current_timestamp_aggiornato_il();

-- 8) Indici aggiuntivi
CREATE INDEX IF NOT EXISTS idx_bando_fonte_id
  ON public.bando (fonte_id);

CREATE INDEX IF NOT EXISTS idx_bando_hash_bando
  ON public.bando (hash_bando);

CREATE INDEX IF NOT EXISTS idx_bando_stato_bando
  ON public.bando (stato_bando);

CREATE INDEX IF NOT EXISTS idx_bando_data_scadenza
  ON public.bando (data_scadenza);

CREATE INDEX IF NOT EXISTS idx_bando_ultimo_scraping_at
  ON public.bando (ultimo_scraping_at DESC);

CREATE INDEX IF NOT EXISTS idx_scraping_log_session_id
  ON public.scraping_log (session_id);

CREATE INDEX IF NOT EXISTS idx_scraping_log_fonte_id
  ON public.scraping_log (fonte_id);

CREATE INDEX IF NOT EXISTS idx_scraping_log_started_at
  ON public.scraping_log (started_at DESC);

CREATE INDEX IF NOT EXISTS idx_bando_storico_bando_id
  ON public.bando_storico (bando_id);

CREATE INDEX IF NOT EXISTS idx_bando_storico_modificato_at
  ON public.bando_storico (modificato_at DESC);

-- 9) Logging, audit e osservabilità (Milestone 10)
ALTER TABLE public.scraping_log
  ADD COLUMN IF NOT EXISTS parent_log_id integer,
  ADD COLUMN IF NOT EXISTS ai_tokens_used integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_calls_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.scraping_log
  DROP CONSTRAINT IF EXISTS scraping_log_parent_log_id_fkey;

ALTER TABLE public.scraping_log
  ADD CONSTRAINT scraping_log_parent_log_id_fkey
    FOREIGN KEY (parent_log_id) REFERENCES public.scraping_log(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_scraping_log_parent_log_id
  ON public.scraping_log (parent_log_id);

-- Vista tabellare di controllo per audit
CREATE OR REPLACE VIEW public.v_scraping_log_run AS
SELECT
  sl.id,
  sl.session_id,
  sl.parent_log_id,
  sl.fonte_id,
  f.titolo                          AS fonte_titolo,
  f.link                            AS fonte_link,
  sl.tipo_operazione,
  sl.stato,
  sl.started_at,
  sl.completed_at,
  sl.tempo_esecuzione_ms,
  sl.bandi_trovati,
  sl.bandi_nuovi,
  sl.bandi_aggiornati,
  sl.bandi_invariati,
  sl.pagine_crawlate,
  sl.ai_calls_count,
  sl.ai_tokens_used,
  sl.errore_tipo,
  sl.errore_messaggio,
  sl.response_summary
FROM public.scraping_log sl
LEFT JOIN public.fonte f ON sl.fonte_id = f.id;

-- =========================================================
-- Milestone: is_bando_confermato (classificazione AI)
-- Indica se il record è un bando/avviso reale (true/false)
-- oppure non ancora classificato (NULL).
-- Valorizzato dal worker AI (run_ai_worker).
-- =========================================================
ALTER TABLE public.bando
  ADD COLUMN IF NOT EXISTS is_bando_confermato BOOLEAN DEFAULT NULL;

-- =========================================================
-- Vista: v_bando_stato_flusso
-- Espone per ogni bando il campo calcolato stato_flusso_completo
-- che riassume in quale fase si trova nel pipeline end-to-end:
--
--   scraping_failed    → stato_processing = 'failed_final'
--   ai_failed          → ai_processing_status = 'failed'
--   ai_pending         → ai_processing_status IN ('queued','processing')
--   ai_needed          → ai_processing_required = TRUE e status non avviato
--   completo           → scraping ok + AI ok (o non richiesta)
--   in_elaborazione    → stato_processing IN ('pending','processing')
--   pronto             → ready, AI not_required, tutto a posto
-- =========================================================
CREATE OR REPLACE VIEW public.v_bando_stato_flusso AS
SELECT
  b.id,
  b.fonte_id,
  b.titolo,
  b.link_bando,
  b.stato_bando,
  b.stato_processing,
  b.ai_processing_required,
  b.ai_processing_status,
  b.is_bando_confermato,
  b.ocr_required,
  b.ocr_status,
  b.primo_scraping_at,
  b.ultimo_scraping_at,
  b.ai_last_attempt_at,
  CASE
    WHEN b.stato_processing = 'failed_final'
      THEN 'scraping_failed'
    WHEN b.ai_processing_status = 'failed'
      THEN 'ai_failed'
    WHEN b.ai_processing_status IN ('queued', 'processing')
      THEN 'ai_in_corso'
    WHEN b.ai_processing_required = TRUE
      AND b.ai_processing_status IN ('not_required')
      THEN 'ai_da_avviare'
    WHEN b.stato_processing IN ('pending', 'processing')
      THEN 'scraping_in_corso'
    WHEN b.stato_processing = 'ready'
      AND b.ai_processing_status IN ('completed', 'not_required')
      AND b.ai_processing_required = FALSE
      THEN 'completo'
    ELSE 'pronto'
  END AS stato_flusso_completo
FROM public.bando b;

COMMIT;
