export interface SelezioneBando {
  id: number;
  codice: string;
  titolo: string;
  descrizione: string;
  descrizione_breve: string;
  figura_ricercata: string;
  num_posti: number | null;
  tipo_procedura: string;
  data_pubblicazione: string;
  data_scadenza: string;
  data_visibilita: string;
  sedi: string[];
  categorie: string[];
  settori: string[];
  enti_riferimento: string[];
  salary_min: number | null;
  salary_max: number | null;
  link_reindirizzamento: string | null;
  calculated_status: 'OPEN' | 'CLOSED' | 'PENDING';
  status_label: string;
  allegato_media_id: string | null;
  status: string;
  article_title: string | null;
  article_subtitle: string | null;
  article_content: string | null;
  article_keywords: string[];
  slug: string;
  created_at: string;
  updated_at: string;
}
